server:
    port: 9092
    servlet:
        session:
            timeout: 30m
            cookie:
                http-only: false
                same-site: none
                secure: true
    reactive:
        session:
            timeout: 30m

default_login:
    user: admin
    password: 123456

spring:
    application:
        name: statistics
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
            config:
                import-check:
                    enabled: false
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/bs
        username: root
        password: justtodox0.
    session:
        redis:
            flush-mode: on_save
            namespace: spring:session
        story-type: redis
    data:
        redis:
            host: 127.0.0.1
            port: 6379
#            password: dkj@zju
    web:
        resources:
            static-locations: file:${web.upload-path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    servlet:
        multipart:
            max-file-size: 100MB


logging:
    level:
        cn.weirdsky.mapper.mapper: debug

web:
    upload-path: E:\_workspace\bs-api\src\main\resources\static
python:

    pythonPath: E:\_workspace\bs-api\src\main\resources\py\
    python: D:\Anaconda3\envs\bs\python.exe
