server:
    port: 9091
    servlet:
        session:
            timeout: 30m
            cookie:
                http-only: false
                same-site: none
                secure: true
    reactive:
        session:
            timeout: 30m
    tomcat:
        mbeanregistry:
            enabled: true
default_login:
    user: admin
    password: 123456

spring:
    application:
        name: department
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/bs
        username: root
        password: justtodox0.
    session:
        redis:
            flush-mode: on_save
            namespace: spring:session
        story-type: redis
    data:
        redis:
            host: 127.0.0.1
            port: 6379
#            password: dkj@zju
    web:
        resources:
            static-locations: file:${web.upload-path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    servlet:
        multipart:
            max-file-size: 100MB
    cloud:
        nacos:
            config:
                import-check:
                    enabled: false

logging:
    level:
        cn.weirdsky.mapper.mapper: debug

web:
    upload-path: E:\_workspace\bs-api\src\main\resources\static
python:

    pythonPath: E:\_workspace\bs-api\src\main\resources\py\
    python: D:\Anaconda3\envs\bs\python.exe
interceptor:
    whitelist:
        ips:
            - "192.168.1.1"
            - "192.168.1.2"
        ports:
            - "9090"
            - "9091"
            - "9092"
            - "9093"
            - "9094"
        userAgents:
            - "Mozilla/5.0"
            - "MyCustomUserAgent"
management:
  server:
    port: 9001
  # 开启 actator 服务
  endpoints:
    web:
      exposure:
        include: '*'
  # 暴露 metrics 端口
  endpoint:
    metrics:
      enabled: true
    # 配置 prometheus 服务
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}